name: Black Code Formatter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies from setup.py
        run: |
          cd feathr_project
          pip install .[dev]

      - name: Run Black
        run: black --check feathr_project --config feathr_project/pyproject.toml
